/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algebrablocks;

import static javafx.scene.paint.Color.color;
import javax.swing.JPanel;

/**
 *
 * @author Jorg3
 */
public class Block extends JPanel{

    /**
     * Creates new form Block
     */
    //Variables   
    private  boolean isLeft;
    protected int initialX;
    protected int initialY;
    protected java.awt.Color initialColor;
    protected int numerator;
    protected int denominator;
    protected boolean isFrac;
   
    public Block() {
        initComponents();
        isFrac = false;
    }

    //Methods...
    protected void setIsFrac(boolean frac) {
        this.isFrac = frac;
    }
    protected void setIsLeft(boolean par){
        this.isLeft = par;
    }
    protected boolean isLeft(){
        return isLeft;
    }
    protected int getInitialX(){
        return initialX;
    }
    protected int getInitialY(){
        return initialY;
    }
    protected void setNumerator(int num) {
        this.numerator = num;
    }
    protected void setDenominator(int denum) {
        this.denominator = denum;
    }
    protected int getNumerator() {
        return numerator;
    }
    protected int getDenominator() {
        return denominator;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(111, 118));
        setMinimumSize(new java.awt.Dimension(111, 118));
        setPreferredSize(new java.awt.Dimension(111, 118));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
